### PR TITLE
Messagingbranch

### PR DESCRIPTION
**Pull request by scboatman**
Added the HTML views and the base elements.

### CODE REVIEW

**Comment by drehmke** [comment]
app.ts is conflicting!

**Comment by scboatman** [comment]
I just added my controllers

Sent via the BlackBerry Hub for Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>

**Comment by drehmke** [comment]
Fixed and merging.

**Comment by drehmke** [comment]
Do you want me to delete the branch @scboatman ?

**Comment by scboatman** [comment]
Yes, please.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Pull request merged**
